# Permalinks
permalink:           pretty

# Setup
title:               Duygu Serbest
tagline:             'Codefolio of a coder.'
description:         'Where Duygu Serbest writes about her struggles, things she learnt and any other stuff related to programming, Data Mining, Machine Learning.'
url:                 http://duygu.io
baseurl:             ''
gems: [jekyll-paginate]
paginate_path: "page:num"
paginate:            5

# About/contact
author:
  name:              Duygu Serbest
  url:               https://twitter.com/serbestduygu


# Custom vars
version:             1.0.0
